//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookbook
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShoppingList
    {
        public int IngredientID { get; set; }
        public string IngredientName { get; set; }
        public Nullable<int> Ammount { get; set; }
        public Nullable<bool> Owned { get; set; }
        public Nullable<int> Recipe { get; set; }
        public Nullable<int> Person { get; set; }
    
        public virtual tblPerson tblPerson { get; set; }
        public virtual tblRecipe tblRecipe { get; set; }
    }
}
